### ISSUE TITLE
Normal pdf in the final plot of the "Random Varialbles" lecture

### ISSUE THREAD

**Issue by tkibbee** [quantopian/research_public#194]
The final code cell in the lecture plots the normal pdf as `sample_distribution = ((1/(sample_std_dev * 2 * np.pi)) * 
                       np.exp(-(x - sample_mean)*(x - sample_mean) / (2 * sample_std_dev * sample_std_dev)))`.

The denominator in the first term should be `np.sqrt(sample_std_dev ** 2 * 2 * np.pi)` instead of `(sample_std_dev * 2 * np.pi)`.

**Comment by mmargenot** [comment]
Corrected here: https://github.com/quantopian/research_public/pull/196
