### ISSUE TITLE
Another visualization tool

### ISSUE THREAD

**Issue by breznak** [quantopian/research_public#39]
Hi guys, 

sorry for OT, I don't know where else to reach relevant developers. 
Would you be interested in using another visualization tool for your charts somewhere? Or letting us know your feedback what are the features you need. We are developing https://github.com/nupic-community/nupic.visualizations , I know Quantopian has its own visualization for data, but some features could be interesting for you: 
* ability to stream remote URLs 
* easy to deploy as JS app
* supports anomaly highlighting
* online monitoring mode

Thanks,

**Comment by gwulfs** [comment]
Pretty satisfied with seaborn + matplot. Thanks for sharing though!
