### ISSUE TITLE
optimal_portfolio() weights seems to return 99% for 1 asset

### ISSUE THREAD

**Issue by schalekamp** [quantopian/research_public#9]
print weights
[[  2.77880107e-09]
 [  3.20322848e-06]
 [  1.54301198e-06]
 [  9.99995251e-01]]   <---- every time optimal_portfolio() runs the solver returns 99% weight on 1 asset

**Comment by twiecki** [comment]
Yeah, this is because there are so few stocks used in this example. Basically, one will always be closest to the efficient frontier. Use more stocks or shrink the means to 1.
